name: Windows Build Only

on:
  workflow_dispatch:

concurrency:
  group: windows-build
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    working-directory: ./Software

jobs:
  build-win:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          cache: true
          cache-key-prefix: install-qt-action-default
          version: 6.6.3
          modules: qtserialport
      - name: Set build vars
        shell: bash
        run: |
          echo "DEFINES += NO_OPENSSL" > build-vars.prf
          echo "TARGET_ARCH = x86_64" >> build-vars.prf
      - name: Build
        shell: cmd
        run: |
          set QTDIR=%Qt6_Dir%
          call scripts\win32\generate_sln.bat
          MSBuild.exe Lightpack.sln /p:Configuration=Release
      - name: Prepare portable bundle
        shell: bash
        run: |
          set -xe
          mkdir -p dist_windows/content
          cp bin/*.exe dist_windows/content/
          cp bin/*.dll dist_windows/content/ || true
          cp -r bin/platforms dist_windows/content/ || true
          cp -r bin/styles dist_windows/content/ || true
          cp -r bin/tls dist_windows/content/ || true
      - name: Upload portable bundle
        uses: actions/upload-artifact@v4
        with:
          name: Prismatik-windows-portable
          path: Software/dist_windows/content
          if-no-files-found: error
